<a href="https://colab.research.google.com/github/gulb15/data_analysis_training/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [ ]:
#array with all elements as 1
one=np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#why use numpy?

#reason1- takes less memory
#reason2- fast
#reason3- convinient to understand

In [ ]:
import numpy as np
import sys 
l=[1,2,3,4,5,6,7,8,9]
print(sys.getsizeof(l)*len(l))

arr=np.array(l)
print(arr.size*arr.itemsize)

1296
72


In [3]:
# #universal function
# np.add
# np.subtract
# np.negative
#np.divide
#np.power
#np.mod

In [4]:
#vectorization- computation in arrays
#fast to convert statemnetss into vector based operation
#vectorization makes operation fast in numpy



In [6]:
a1=np.array([[1,1,1],[2,2,2],[3,3,3]])
a2=np.array([[1,1,1],[2,2,2],[3,3,3]])
a1+a2

array([[2, 2, 2],
       [4, 4, 4],
       [6, 6, 6]])

In [8]:
a1-a2 #vector operation

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
#absolute function
arr=np.array([-1,0,2,-1,-7])
np.absolute(arr)

array([1, 0, 2, 1, 7])

In [13]:
#expoennt
x=[1,2,3]
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [14]:
#ln(x)
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [15]:
np.log2(x)

array([0.       , 1.       , 1.5849625])

In [16]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125])

In [17]:
np.exp2(x)

array([2., 4., 8.])

In [18]:
#normalization of data in visualization
#there log n ln n exp is used

In [20]:
# #universal func
# 1. specifying output
x=np.arange(5)
y=np.empty(5)



In [22]:


#2. aggregation(reduce method- returns single result out of all elemets in array by applying any operation)
x=np.arange(1,11)
np.add.reduce(x)


55

In [24]:
np.add.accumulate(x) #prints all intermediate results of the reduce function

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [25]:
#np.cumprod,np.cumsum,np.sum,np.prod
np.sum(x)

55

In [33]:
a2

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [30]:
np.sum?

In [32]:
np.sum([[0, 1], [0, 5]])

6

In [34]:
# # #numpy provides many aggregation functions
# sum,
# mean,
# std,
# var,
# min,
# max,
# argmin,
# argmax,
# median,
# percentile,
# any(for true false),
# np.all(for whether all elements are true or not)

In [35]:
np.mean(a1,axis=0)

array([2., 2., 2.])

In [36]:
a1

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [37]:
#variance
np.var(a1)

0.6666666666666666

In [39]:
x=np.arange(1,101).reshape(10,10)
print(x)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [40]:
x=np.arange(1,101)
print(x)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [43]:
x=np.arange(1,20)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [47]:
x=np.arange(1,21).reshape(2,10)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [49]:
x[:,0]

array([ 1, 11])

In [51]:
np.mean(x[:,0])

6.0

In [52]:
x=np.array([23,34,45,np.nan])
x

array([23., 34., 45., nan])

In [54]:
np.mean(x)

nan

In [55]:
np.nanmean(x)

34.0

In [56]:
# #how to create your own universal function
# add with lib called frompyfunc() method
# takes agruments
# 1. function
# 2. inputs
# 3. outputs


In [59]:
def myufunc(x):
  return x**3

In [60]:
x=np.arange(1,11)
cube= np.frompyfunc(myufunc,1,1)
cube(x)

array([1, 8, 27, 64, 125, 216, 343, 512, 729, 1000], dtype=object)

In [64]:
type(cube)   #to check if is it a ufunc

numpy.ufunc

In [66]:
type(np.add)    #inbuilt universal ufunc

numpy.ufunc

In [69]:
#create a ufunc which gives true when number is even otherwise false
def myfunc(x):
  if(x%2==0):
    return True
  else:
    return False

In [70]:
x=np.arange(1,11)
ans=np.frompyfunc(myfunc,1,1)
ans

<ufunc '? (vectorized)'>

In [72]:
y=np.array([12,23,34,45,56])
e=np.frompyfunc(myfunc,1,1)
type(e)

numpy.ufunc

In [73]:
e(x)

array([False, True, False, True, False, True, False, True, False, True],
      dtype=object)

In [74]:
e(y)

array([True, False, True, False, True], dtype=object)

In [75]:
type(myfunc)

function

In [78]:
for i in range(np.size(x)):
  print(myfunc(x[i]))

False
True
False
True
False
True
False
True
False
True


In [79]:
#SEARCHING IN ARRAY

In [83]:
x=np.arange(400,999)
np.where(x==499)

(array([99]),)

In [84]:
np.where(x>550)

(array([151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
        164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176,
        177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
        190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
        203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
        216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
        229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
        242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
        255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267,
        268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280,
        281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293,
        294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306,
        307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319,
        320, 321, 322, 323, 324, 325, 326, 327, 328

In [88]:
#FAST SORTING IN NUMPY : np.sort and np.argsort
#complexity is O(nlogn)

In [93]:
#FILTERING ARRAYS
x=np.array([1,2,3,4,5,6])
f=[True,False,True,False,True,False]
x[f]

array([1, 3, 5])

In [94]:
x[x%2==0]

array([2, 4, 6])