<a href="https://colab.research.google.com/github/gulb15/data_analysis_training/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#array with all elements as 1
one=np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#why use numpy?

#reason1- takes less memory
#reason2- fast
#reason3- convinient to understand

In [ ]:
import numpy as np
import sys 
l=[1,2,3,4,5,6,7,8,9]
print(sys.getsizeof(l)*len(l))

arr=np.array(l)
print(arr.size*arr.itemsize)

1296
72


In [ ]:
# #universal function
# np.add
# np.subtract
# np.negative
#np.divide
#np.power
#np.mod

In [ ]:
#vectorization- computation in arrays
#fast to convert statemnetss into vector based operation
#vectorization makes operation fast in numpy



In [ ]:
a1=np.array([[1,1,1],[2,2,2],[3,3,3]])
a2=np.array([[1,1,1],[2,2,2],[3,3,3]])
a1+a2

array([[2, 2, 2],
       [4, 4, 4],
       [6, 6, 6]])

In [ ]:
a1-a2 #vector operation

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
#absolute function
arr=np.array([-1,0,2,-1,-7])
np.absolute(arr)

array([1, 0, 2, 1, 7])

In [ ]:
#expoennt
x=[1,2,3]
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
#ln(x)
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.log2(x)

array([0.       , 1.       , 1.5849625])

In [ ]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125])

In [ ]:
np.exp2(x)

array([2., 4., 8.])

In [ ]:
#normalization of data in visualization
#there log n ln n exp is used

In [ ]:
# #universal func
# 1. specifying output
x=np.arange(5)
y=np.empty(5)



In [ ]:


#2. aggregation(reduce method- returns single result out of all elemets in array by applying any operation)
x=np.arange(1,11)
np.add.reduce(x)


55

In [ ]:
np.add.accumulate(x) #prints all intermediate results of the reduce function

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [ ]:
#np.cumprod,np.cumsum,np.sum,np.prod
np.sum(x)

55

In [ ]:
a2

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
np.sum?

In [ ]:
np.sum([[0, 1], [0, 5]])

6

In [ ]:
# # #numpy provides many aggregation functions
# sum,
# mean,
# std,
# var,
# min,
# max,
# argmin,
# argmax,
# median,
# percentile,
# any(for true false),
# np.all(for whether all elements are true or not)

In [ ]:
np.mean(a1,axis=0)

array([2., 2., 2.])

In [ ]:
a1

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
#variance
np.var(a1)

0.6666666666666666

In [ ]:
x=np.arange(1,101).reshape(10,10)
print(x)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [ ]:
x=np.arange(1,101)
print(x)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
x=np.arange(1,20)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
x=np.arange(1,21).reshape(2,10)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
x[:,0]

array([ 1, 11])

In [ ]:
np.mean(x[:,0])

6.0

In [ ]:
x=np.array([23,34,45,np.nan])
x

array([23., 34., 45., nan])

In [ ]:
np.mean(x)

nan

In [ ]:
np.nanmean(x)

34.0

In [ ]:
# #how to create your own universal function
# add with lib called frompyfunc() method
# takes agruments
# 1. function
# 2. inputs
# 3. outputs


In [ ]:
def myufunc(x):
  return x**3

In [ ]:
x=np.arange(1,11)
cube= np.frompyfunc(myufunc,1,1)
cube(x)

array([1, 8, 27, 64, 125, 216, 343, 512, 729, 1000], dtype=object)

In [ ]:
type(cube)   #to check if is it a ufunc

numpy.ufunc

In [ ]:
type(np.add)    #inbuilt universal ufunc

numpy.ufunc

In [ ]:
#create a ufunc which gives true when number is even otherwise false
def myfunc(x):
  if(x%2==0):
    return True
  else:
    return False

In [ ]:
x=np.arange(1,11)
ans=np.frompyfunc(myfunc,1,1)
ans

<ufunc '? (vectorized)'>

In [ ]:
y=np.array([12,23,34,45,56])
e=np.frompyfunc(myfunc,1,1)
type(e)

numpy.ufunc

In [ ]:
e(x)

array([False, True, False, True, False, True, False, True, False, True],
      dtype=object)

In [ ]:
e(y)

array([True, False, True, False, True], dtype=object)

In [ ]:
type(myfunc)

function

In [ ]:
for i in range(np.size(x)):
  print(myfunc(x[i]))

False
True
False
True
False
True
False
True
False
True


In [ ]:
#SEARCHING IN ARRAY

In [ ]:
x=np.arange(400,999)
np.where(x==499)

(array([99]),)

In [ ]:
np.where(x>550)

(array([151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
        164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176,
        177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
        190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
        203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
        216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
        229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
        242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
        255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267,
        268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280,
        281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293,
        294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306,
        307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319,
        320, 321, 322, 323, 324, 325, 326, 327, 328

In [ ]:
#FAST SORTING IN NUMPY : np.sort and np.argsort
#complexity is O(nlogn)

In [ ]:
#FILTERING ARRAYS
x=np.array([1,2,3,4,5,6])
f=[True,False,True,False,True,False]
x[f]

array([1, 3, 5])

In [ ]:
x[x%2==0]

array([2, 4, 6])

In [ ]:
x=list(range(1,10))

In [ ]:
type(x)

list

In [1]:
#Reshaping method

In [3]:
import numpy as np

In [4]:
x=np.arange(1,10)

In [5]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
y=x.reshape(3,3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
y.base

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#flattening of array

In [13]:
x= np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
x.reshape(-1) # -1 is passed

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#transpose of array

In [18]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
x.T #transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [23]:
#rotation of array
#numpy.rot90(m,k=1,axes=(0,1))
# three parameters
#m - array
#k - 
#axes - 

In [29]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
y = np.rot90(x)

In [31]:
y

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [33]:
y= np.rot90(x,k=2)
y

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [35]:
#joining of arrays
# np.concatenate
# np.vstack - row wise
# np.hstack - column wise stacking

In [37]:
x1 = np.arange(1,10).reshape(3,3)
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
x2 = np.arange(21,30).reshape(3,3)
x2

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [40]:
np.concatenate((x1,x2),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [41]:
np.concatenate((x1,x2),axis=1)

array([[ 1,  2,  3, 21, 22, 23],
       [ 4,  5,  6, 24, 25, 26],
       [ 7,  8,  9, 27, 28, 29]])

In [43]:
x1 = np.arange(1,11).reshape(2,5)
x1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
x2 = np.arange(21,31).reshape(5,2)
x2

array([[21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30]])

In [47]:
np.concatenate((x1,x2),axis = 0)
#this means that this can be used only when axis matches..
# 2 x 5 and 5 X 2 == then it cant be done! ( for axis 0)
# but for axis 1 it can be done
#either row or column should be same

ValueError: ignored

In [48]:
x1 = np.arange(1,9).reshape(2,4)
x1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
x2 = np.arange(1,11).reshape(2,5)
x2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
# x1 and x2 can be concatenated through axis 1
np.concatenate((x1,x2),axis =1)

array([[ 1,  2,  3,  4,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  6,  7,  8,  9, 10]])

In [52]:
x1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
x2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [56]:
np.hstack((x1,x2))

array([[ 1,  2,  3,  4,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  6,  7,  8,  9, 10]])

In [61]:
#splitting in array

In [62]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
np.split(x, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [65]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
x = np.arange(1,13).reshape(2,6)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [69]:
np.split(x,[3,4], axis =1) #x[0:3], x[3:4], x[4:]

[array([[1, 2, 3],
        [7, 8, 9]]), array([[ 4],
        [10]]), array([[ 5,  6],
        [11, 12]])]

In [70]:
x = np.arange(1,13).reshape(6,2)
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [73]:
np.split(x,6)

[array([[1, 2]]),
 array([[3, 4]]),
 array([[5, 6]]),
 array([[7, 8]]),
 array([[ 9, 10]]),
 array([[11, 12]])]

In [74]:
np.split(x,[3,5]) # x[0:3], x[3:5] , x[5:]

[array([[1, 2],
        [3, 4],
        [5, 6]]), array([[ 7,  8],
        [ 9, 10]]), array([[11, 12]])]

In [75]:
# numpy.hsplit()
#split a array into multiplle sub array horizontally
# np.hsplit()


In [76]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [77]:
np.hsplit(x,2)

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]), array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]])]

In [78]:
np.vsplit(x,2)

[array([[1, 2],
        [3, 4],
        [5, 6]]), array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [79]:
np.vsplit(x,3)

[array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]), array([[ 9, 10],
        [11, 12]])]

In [80]:
# vsplit same as x=1
# hsplit same as x=0

'\nbool_ \nint_\nintc_\nintp_\n'

#data types in ndarrays

bool_ 
int_
intc_
intp_
.
.
.
.

In [86]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
x.dtype

dtype('int64')

In [90]:
#to cast to any numoy datatype
y = x.astype(np.int8)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [91]:
# casting
x = np.array([1,2,3,4])
y = x.astype(np.int32)
y


array([1, 2, 3, 4], dtype=int32)

In [92]:
x= np.array([12332434456656,99999999,455456546])
x

array([12332434456656,       99999999,      455456546])

In [94]:
x.dtype

dtype('int64')

In [95]:
y = np.array([1,2,3])
y.dtype

dtype('int64')

In [98]:
x = np.arange(1,10)
y = np.array([1,3,5,3,5,4,17,8,11])
x<y

array([False,  True,  True, False, False, False,  True, False,  True])

In [99]:
x*y

array([  1,   6,  15,  12,  25,  24, 119,  64,  99])

In [100]:
x==y

array([ True, False, False, False,  True, False, False,  True, False])